//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string PublicationDate { get; set; }
        public string Genre { get; set; }
    
        public virtual LibraryCard LibraryCard { get; set; }

        public Book() { }

        public Book(Book book)
        {
            Title = book.Title;
            Author = book.Author;
            PublicationDate = book.PublicationDate;
            Genre = book.Genre;
        }

        public Book(string title, string author, string publicationDate, string genre)
        {
            Title = title;
            Author = author;
            PublicationDate = publicationDate;
            Genre = genre;
        }
    }
}
