//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student : User
    {
        public string Group { get; set; }
        public int Course { get; set; }
        public string Faculty { get; set; }
        public int RegistrationPacket { get; set; }
    
        public virtual LibraryCard LibraryCard { get; set; }

        public Student() { }

        public Student(User user, string group, int course, string faculty, int registraionPacket) : base(user)
        {
            Group = group;
            Course = course;
            Faculty = faculty;
            RegistrationPacket = registraionPacket;
        }

        public override void UpdateUser(User user)
        {
            base.UpdateUser(user);
        }
    }
}
