//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FIO { get; set; }
        public bool Admin { get; set; }

        public User() { }

        public User(User user)
        {
            Id = user.Id;
            Login = user.Login;
            Password = user.Password;
            FIO = user.FIO;
            Admin = user.Admin;
        }

        public User(string login, string password, string FIO)
        {
            Login = login;
            Password = password;
            this.FIO = FIO;
            Admin = false;
        }

        public virtual void UpdateUser(User user)
        {
            Id = user.Id;
            Login = user.Login;
            Password = user.Password;
            FIO = user.FIO;
            Admin = user.Admin;
        }
    }
}
